// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

//import java.util.concurrent.BlockingQueue;

import edu.wpi.first.networktables.NetworkTable;
//import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DigitalInput;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
//import frc.robot.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */

public class ADS extends SubsystemBase {

    NetworkTable ads_table;
    int mode = 0;

    DigitalInput m_front_sensor = new DigitalInput(5);
    DigitalInput m_rear_sensor = new DigitalInput(6);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    NetworkTable DataNAVX;
    /**
    * Automatic Defense System
    */
    public ADS() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        ads_table = inst.getTable("SmartDashboard").getSubTable("ads");

        DataNAVX= inst.getTable("SmartDashboard").getSubTable("DataNAVX");

    }


    @Override
    public void periodic() {

        ads_table.getEntry("front_sensors").setBoolean(getFrontSensors());
        ads_table.getEntry("rear_sensors").setBoolean(getRearSensors());


    }

    public boolean getFrontSensors(){
        return m_front_sensor.get();
    }

    public boolean getRearSensors(){
        return m_rear_sensor.get();
    }


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
